name: Laravel Docs Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:  # Manual trigger

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Check for documentation updates
      id: check-updates
      continue-on-error: true
      run: |
        set +e
        python docs_updater.py --version 12.x
        UPDATE_NEEDED=$?
        if [ "$UPDATE_NEEDED" -eq 1 ]; then 
          echo "updates_available=true" >> $GITHUB_OUTPUT
        else
          echo "updates_available=false" >> $GITHUB_OUTPUT
        fi
    - name: Close existing pull requests
      if: steps.check-updates.outputs.updates_available == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pulls = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            head: 'update-laravel-docs'
          });
          
          for (const pull of pulls.data) {
            if (pull.title === 'Update Laravel documentation') {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull.number,
                state: 'closed'
              });
              console.log(`Closed existing PR #${pull.number}`);
            }
          }
    - name: Create Pull Request
      if: steps.check-updates.outputs.updates_available == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update Laravel documentation to latest version'
        title: 'Update Laravel documentation'
        body: 'Automated PR to update Laravel documentation to the latest version.'
        branch: update-laravel-docs