name: Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.0.0

jobs:
  build-docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Extract tag name
      id: extract_tag
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          # For manual triggers or other cases, use latest git tag or default
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        fi
    - name: 🔑 Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}